# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  build: 
    name: Build Project 
    runs-on: macOS-latest
    steps:
    - name: Configurando Ambiente
      uses: actions/checkout@v1

    - name: Clean & Build & Test
      run: xcodebuild clean build test -project Momondo/Momondo.xcodeproj -scheme Momondo -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14"
